name: NetFx

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet Packages
      run: nuget restore CallTracking.sln

    - name: Set up local configuration
      run: copy "CallTracking.Web\Local.config.sample" "CallTracking.Web\Local.config"

    - name: Build Web App
      run: msbuild CallTracking.sln /verbosity:minimal

    - name: Run Tests with NUnit Console
      run: .\packages\NUnit.ConsoleRunner.3.12.0\tools\nunit3-console CallTracking.Web.Test\bin\Debug\CallTracking.Web.Test.dll
